rebuildukraine/rebuildukraine/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('slavaukraine/', include('slavaukraine.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rebuildukraine/slavaukraine/urls.py
from django.urls import include, path
from django.views.generic import DeleteView

from . import views
from .views import ProposalList, ProposalUpdate, EnterpriseProposalList, EnterpriseUpdate, PersonUpdate

app_name='slavaukraine'
urlpatterns = [
    # Paginas de apresentação da página
    path("", views.home, name="home"),
    # mais info de voluntario
    path("volunteer", views.volunteer, name="volunteer"),
    # mais info de empresas
    path("enterprise",views.enterprise, name="enterprise"),
    # Contactos
    path("contacts",views.contacts, name="contacts"),
    # Login
    path("login/",views.login_view, name="login"),
    # Logout
    path("logout/",views.logout_view, name="logout"),
    # Area reservada onde visualiza conta, mensagens e propostas
    path("reserved", views.reserved, name="reserved"),
    # Registo de Empresa
    path("register_enterprise", views.enterpriseRegistration_view, name="register_enterprise"),
    # Registo de Voluntario
    path("register_volunteer", views.volunteerRegistration_view, name="register_volunteer"),
    # Registo de proposta
    path("reserved/regist_proposal", views.proposal_create_view, name="regist_proposal"),
    # Visualizacao de proposta com Opção de Inscrição/Add aos Favoritos
    path("proposal/<int:proposal_id>", views.viewProposal, name="proposal"),
    # Remoção da Proposta das Inscrições
    path("remProposal/<int:proposal_id>", views.removeProposalSubscription, name="removesubscription"),
    # Adicionar aos favoritos
    path('reserverd/<int:proposal_id>/favorite_proposal', views.favorite_proposal, name="favorite_proposal"),
    # Remoção da Proposta dos Favoritos
    path("remFavorite/<int:proposal_id>", views.removeFavoriteProposal, name="removefavorite"),
    # Edição de utilizador
    path("reserved/editPerson/<int:pk>/", PersonUpdate.as_view(), name='edit_person'),
        #O PATH em baixo é um auxiliar do regist_proposal, na dropdown dinâmica;
        path("ajax/load-cities/", views.load_cities, name="ajax_load_cities"),
    # Edição user Empresarial
    path("reserved/editEnterprise/<int:pk>/", EnterpriseUpdate.as_view(), name='enterprise_edit'),
    # Edição proposta da empresa
    path("editProposal/<int:pk>/", ProposalUpdate.as_view(), name='edit_proposal'),
    # Listar todas as propostas
    path("listproposals/", ProposalList.as_view(), name='listproposals'),
    # Empresa fecha proposta
    path("closeProposal/<int:pk>/", views.closeProposal, name='close_proposal'),
    # Empresa reabre proposta
    path("reopenProposal/<int:pk>/", views.reopenProposal, name='reopen_proposal'),
    # Eliminação de proposta pela empresa
    path("deleteProposal/<int:pk>/", views.deleteProposal, name='delete_proposal'),
    # Eliminação de qualquer tipo de utilizador
    path("deleteUser/<int:pk>/", views.deleteUser, name='delete_user'),
    # #Área de Listagens
    # path("listed_proposals/<int:pk>/", EnterpriseProposalList.as_view(), name='list_enterpriseproposals'),

    # Pagina de perfil de utilizador
    path("reserved/user/<int:user_id>", views.viewUser, name="user"),

    # --------------------------------------------------------------------------------

    # --------------------------- Serviço de Emails ----------------------------------

    # --------------------------------------------------------------------------------


    # Criar uma nova mensagem para o user
    path("reserved/create_new_message/<int:recipient>", views.newMessage, name="create_new_message"),

    # Visualizacao e resposta à mensagem
    path("reserved/message/<int:topic_id>", views.replyMessage, name="message"),

    
    #Adicionar aos favoritos
    path('<int:proposal_id>/favorite_proposal', views.favorite_proposal, name="favorite_proposal"),



]

rebuildukraine/slavaukraine/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Model
from django.forms import DateInput
from django.utils import timezone
from django import forms

#Utilizadores da Aplicação



class MyPersonManager(BaseUserManager):
    #Se adicionar nos REQUIRED arguments do USER mais argumentos, tenho que acrescentar aqui também
    def create_user(self, email, username, password):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)
        return user



class Person(AbstractBaseUser):
    MALE='Male'
    FEMALE='Female'
    BINARY='Binary'
    NONBINARY='Nonbinary'
    OTHER='Other'
    GENDER = [
        (MALE,'Male'),
        (FEMALE,'Female'),
        (BINARY,'Binary'),
        (NONBINARY,'Nonbinary'),
        (OTHER,'Other'),
    ]
    email                       =models.EmailField(verbose_name="email", max_length=60, unique=True)
    username                    =models.CharField(max_length=30, unique=True)
    profile_image               =models.ImageField(null=True,blank=True,verbose_name="Imagem de perfil")
    taxnumber                   =models.CharField( unique=True, max_length=10, validators=[RegexValidator(r'^\d{1,10}$')],verbose_name="Número de Contribuinte")
    date_joined                 =models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login                  =models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin                    =models.BooleanField(default=False)
    is_active                   = models.BooleanField(default=True)
    is_staff                    = models.BooleanField(default=False)
    is_superuser                = models.BooleanField(default=False)
    is_enterprise               = models.BooleanField(null=True, blank=True)
    is_person                   = models.BooleanField(null=True, blank=True)
    first_name                  = models.CharField(max_length=30,null=True, blank=True, verbose_name="Nome")
    last_name                   = models.CharField(max_length=30,null=True, blank=True, verbose_name="Último nome")
    gender                      = models.CharField(max_length=10,choices=GENDER,null=True, blank=True, verbose_name="Género")
    address                     = models.CharField(max_length=150,null=True, blank=True, verbose_name="Morada")
    birth                       = models.DateField(null=True, blank=True, verbose_name="Data de nascimento")
#Se quisermos o login com o username invés do e-mail é substituir aqui
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = MyPersonManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return  self.is_admin

    def has_module_perms(self, app_label):
        return True



    def setEnterprise(self):
        self.is_enterprise=True;
        self.is_person=False;

    def setPerson(self):
        self.is_enterprise=False;
        self.is_person=True;

    class Meta:
        abstract = False
        verbose_name= "Utilizadores singulares"
        verbose_name_plural= "Utilizadores singulares"


#Neste momento faz sentido ser um tuplo porque só temos um país. Contudo se virmos que há potencial
#para acrescentar países, criamos um método para adicionar campos e retiramos o tuplo;

class Country(models.Model):
    name                     =models.CharField(max_length=25, verbose_name='País')#,choices=COUNTRIES

    def __str__(self):
        return self.name

    class Meta:
        verbose_name= "País"
        verbose_name_plural= "Países"



class City(models.Model):
    country                     =models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='País')
    name                        =models.CharField(max_length=25, verbose_name='Cidade')#choices=CITIES

    def __str__(self):
        return self.name

    class Meta:
        verbose_name= "Cidade"
        verbose_name_plural= "Cidades"


class Expertise(models.Model):
    name            =models.CharField(max_length=250, verbose_name='Especialidade')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name= "Especialização"
        verbose_name_plural= "Especializações"

class Specialization(models.Model):
    expertise                   = models.ForeignKey(Expertise,on_delete=models.CASCADE, verbose_name='Especialidade')
    person                      = models.ForeignKey(Person,on_delete=models.CASCADE, verbose_name='Voluntário')

    def __str__(self):
        return self.person.username

    class Meta:
        verbose_name= "Voluntário especialista"
        verbose_name_plural= "Voluntários especializados"

#Rever se acham que vale a pena só a cidade
class Proposal(models.Model):
    enterprise                  =models.ForeignKey(Person, on_delete=models.CASCADE)
    country                     =models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    city                        =models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)
    expertiseNeeded             =models.ForeignKey(Expertise,on_delete=models.CASCADE, blank=True, null=True, verbose_name='Especialidade')
    title                       =models.CharField(max_length=50,verbose_name='Título')
    description                 =models.CharField(max_length=150,verbose_name='Descrição')
    closed                      =models.BooleanField(default=False)

    def __str__(self):
        return self.enterprise.username
    
    def register(self, user):
        registration = Registration.objects.create(person=user, proposal=self)
        return "Empresa: "+self.enterprise.username+" | Título: "+self.title

    def unregister(self, user):
        registration = Registration.objects.get(person=user, proposal=self)
        registration.delete()
        
    def subscribe(self, user):
        registration = Favorites.objects.create(person=user, proposal=self)

    def unsubscribe(self, user):
        registration = Favorites.objects.get(person=user, proposal=self)
        registration.delete()
        
    class Meta:
        verbose_name= "Proposta de voluntariado"
        verbose_name_plural= "Propostas de voluntariado"

class Favorites(models.Model):
    person                      = models.ForeignKey(Person,on_delete=models.CASCADE, verbose_name='Voluntário')
    proposal                    = models.ForeignKey(Proposal,on_delete=models.CASCADE, verbose_name='Proposta')

    def __str__(self):
        return self.person.username

    class Meta:
        verbose_name= "Favorito"
        verbose_name_plural= "Favoritos"

class Registration(models.Model):
    person                      =models.ForeignKey(Person,on_delete=models.CASCADE)
    proposal                    =models.ForeignKey(Proposal,on_delete=models.CASCADE)

    def __str__(self):
        return self.person.username

    class Meta:
        verbose_name= "Registo em voluntariado"
        verbose_name_plural= "Registos em voluntariados"

class TopicMessage(models.Model):
    subjet = models.CharField(max_length=150)
    sender = models.ForeignKey(Person,on_delete=models.CASCADE,related_name='sender_top')
    receiver = models.ForeignKey(Person,on_delete=models.CASCADE,related_name='receiver_top')
    isRead = models.BooleanField(null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pk

    class Meta:
        verbose_name= "Mensage"
        verbose_name_plural= "Mensagens"


class Answers(models.Model):
    topic = models.ForeignKey(TopicMessage,on_delete=models.CASCADE)
    message = models.CharField(max_length=250)
    sender = models.ForeignKey(Person,on_delete=models.CASCADE,related_name='sender_ans')
    receiver = models.ForeignKey(Person, on_delete=models.CASCADE,related_name='receiver_ans' )
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pk

    class Meta:
        verbose_name= "Resposta"
        verbose_name_plural= "Respostas"

rebuildukraine/slavaukraine/templates/slavaukraine/deleteproposal.html
<body>
<form action="" method="POST">

    <p class="lead">
        Deseja apagar definitivamente a proposta <strong>"{{ object.title }}"</strong> em <strong>{{ object.city }}</strong>?
    </p>
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Apagar</button>

</form>

rebuildukraine/slavaukraine/templates/slavaukraine/editproposal.html
{% extends "slavaukraine/template_box.html" %}
{% load static %}
{% block box %}
<div class="container position-relative">

    <div class="text-center">
        <br>
        <h2>Edição de Utilizador</h2>
        <br>
        <br>
    </div>
    <div class="row">
        <div class="col-3">
            <br>
        </div>
        <div class="col-6 align-content-center color-uk">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                    <br>
                <button type="submit" class="btn btn-outline-yellow btn-sm carrousel-button">Guardar</button>
                <br><br>
            </form>
                  <br>
        </div>
        <div class="col-3">
            <br>

                <br><br>

        </div>
    </div>
</div>
{% endblock %}

rebuildukraine/slavaukraine/templates/slavaukraine/regist_proposal.html
{% extends "slavaukraine/template_box.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block box %}
<div class="container position-relative">

    <div class="text-center">
        <br>
        <h2>Criação de Proposta</h2>
        <br>
    </div>
    <div class="row">
        <div class="col-3">
            <br>
        </div>

        <div class="col-6 align-content-center">
            <form class="color-uk" method="post" id="proposalForm"
                  data-cities-url="{% url 'slavaukraine:ajax_load_cities' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <div class="d-inline-flex w-100 justify-content-end">
                    <button type="submit" class="btn-sm btn-primary text-right carrousel-button-uk">Gravar Proposta
                    </button>
                </div>
            </form>
            <br>
            <br>
        </div>
        <div class="col-3">
            <br>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        //gets the ID of the selected country
        $("#id_country").change(function () {
            const url = $("#proposalForm").attr("data-cities-url");
            const countryId = $(this).val(); //Gets the selected country from the HTML input

            $.ajax({ //initializes an AJAX request
                url: url,   //Sets the url of the request (= /proposals/ajax/load-cities)
                data: {
                    'country_id': countryId //Adds the country id to the GET parameters
                },
                success: function (data) { // 'data' will be the return of the 'load_cities view function
                    //Way of debug the info that HTML is receiving: console.log(data);
                    $("#id_city").html(data); // Replaces the contents of the city input with the data that came from the server!
                    /*
                                        let html_data='<option value="">------------</option>';
                                        data.forEach(function (city){
                                            html_data += '<option value="$(city.id)">$(city.name)</option>'
                                        });
                                        console.log(html_data);
                                        $("#id_city").html(html_data)*/
                }
            })

        })
    </script>
</div>
{% endblock%}

rebuildukraine/slavaukraine/templates/slavaukraine/register_enterprise.html
{% extends "slavaukraine/template.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block main %}
    <div>
        <section class="position-relative py-4 py-xl-5">
            <div class="container">
                <div class="row mb-5">
                    <div class="col-md-8 col-xl-6 text-center mx-auto">
                        <p class="w-lg-50"></p>
                    </div>
                </div>
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6 col-xl-4 register-size-form">
                        <div class="card mb-6">
                            <div class="card-body d-flex flex-column align-items-center register-size-card">
                                <h2>Registo</h2>
                                <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                         viewBox="0 0 16 16" class="bi bi-person">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                    </svg>
                                </div>

                                {% block content %}

                                    <h2>Registo de empresa</h2>
                                    <form action="{% url 'slavaukraine:register_enterprise' %}" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}

                                        {{ enterpriseregistration_form|crispy }}

                                        <br>
                                        <button class="btn btn-primary d-block w-100" type="submit">Registar</button>
                                    </form>

                                {% endblock content %}
                                <br>
                                <a class="text-muted" href="{% url 'slavaukraine:login' %}">Já tem registo?</a>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

rebuildukraine/slavaukraine/templates/slavaukraine/reserved.html
{% extends "slavaukraine/template_box.html" %}
{% load static %}
{% block box %}
<br>
<ul class="nav nav-pills mb-3 reserved-page-buttons" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill"
                data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home"
                aria-selected="true">Conta
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-messages-tab" data-bs-toggle="pill"
                data-bs-target="#pills-messages" type="button" role="tab"
                aria-controls="pills-messages" aria-selected="false">Mensagens
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-projects-tab" data-bs-toggle="pill"
                data-bs-target="#pills-projects" type="button" role="tab"
                aria-controls="pills-projects" aria-selected="false">
            {% if user.is_person %} Projectos Inscritos
            {% elif user.is_enterprise %} Projetos Registados
            {% endif %}
        </button>
    </li>
    {% if user.is_person %}
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-saved-tab" data-bs-toggle="pill"
                data-bs-target="#pills-saved" type="button" role="tab"
                aria-controls="pills-saved" aria-selected="false">Favoritos
        </button>
    </li>
    {% endif %}
</ul>

<div class="tab-content reserved-page-information" id="pills-tabContent">
    <!-- User -->
    <div class="tab-pane fade show active reserved-page-information" id="pills-home" role="tabpanel"
         aria-labelledby="pills-home-tab">
        <div class="row d-flex justify-content-center">
            <div class="col-md-3 col-lg-3 col-xl-3">
                <div class="d-flex flex-column justify-content-sm-start align-items-start h-100 contacts-contacts">
                    <div class="d-flex align-items-center p-3 ">
                        {% if user.profile_image  %}
                        <img class="rounded-circle flex-shrink-0 me-3 fit-cover"
                             width="150"
                             height="150"
                             src="{{ user.profile_image.url }}">
                        {% else %}
                        <img class="rounded-circle flex-shrink-0 me-3 fit-cover"
                             width="150"
                             height="150"
                             src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-lg-9 col-xl-9">
                <div>
                    <br>
                    {% if user.is_enterprise %}
                    <div class="mb-3">
                        {% if user.first_name %}
                        <p>Nome: {{ user.first_name }} {{ user.last_name }}</p>
                        {% endif %}
                        <p>Email: {{ user.email }}</p>
                        <p>Número de contribuinte: {{ user.taxnumber }}</p>
                        <p>Morada: {{ user.address }}</p>
                        <p>Date joined: {{ user.date_joined }}</p>
                        <br>
                    </div>
                    <div>
                        <a class="btn btn-primary text-right carrousel-button-uk" role="button"
                           href="{% url 'slavaukraine:enterprise_edit' user.pk %}">Alterar</a>
                    </div>
                    {% endif %}

                    {% if user.is_person %}
                    <div>
                        {% if user.first_name %}
                        <p>Nome Pessoa: {{ user.first_name }} {{ user.last_name }}</p>
                        {% endif %}
                        <p>Email: {{ user.email }}</p>
                        <p>Número de contribuinte: {{ user.taxnumber }}</p>
                        <p>Morada: {{ user.address }}</p>
                        <p>Data de nascimento: {{ user.birth }}</p>
                        <p>Date joined: {{ user.date_joined }}</p>
                        <br>
                    </div>
                    <div>
                        <a class="btn btn-primary text-right carrousel-button-uk" role="button"
                           href="{% url 'slavaukraine:edit_person' request.user.id %}">Alterar</a>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>


    </div>
    <!-- Messages-->
    <div class="tab-pane fade reserved-page-information" id="pills-messages" role="tabpanel"
         aria-labelledby="pills-messages-tab">
        <div class="list-group">
            <table id="table_id2" class="display message-page-mtitle">
                <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Criado por</th>
                    <th>Data</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    {% for message in list %}
                    {% if message.subjet != "None" %}
                    <td class="list-group-item list-group-item-action">
                        <p class="mb-1 message-page-stitle">{{ message.subjet }}</p>
                    </td>
                    <td>
                        <p class="mb-1 message-page-stitle">&nbsp;&nbsp; &nbsp;&nbsp;{{ message.receiver.first_name }}
                        </p>
                    </td>
                    <td>
                        <div class="d-flex w-100 justify-content-between">
                            <small class="text-muted">&nbsp; {{ message.date }}</small>

                            <a class="btn-sm btn-primary text-right carrousel-button-uk reserved-remove-underline" role="button"
                               href="{% url 'slavaukraine:message' message.id  %}">Ver / Responder</a>

                        </div>
                    </td>


                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <br>
        </div>


    </div>
    <!-- Projetos -->
    <div class="tab-pane fade reserved-page-information" id="pills-projects" role="tabpanel"
         aria-labelledby="pills-projects-tab">
        <div class="list-group">
            <table id="table_id" class="display message-page-mtitle">
                <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Especialidade</th>
                    <th>Localização</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    {% if user.is_enterprise %}
                    {% for proposal in proposals_enterprise %}
                    {% if proposal.title != "None" %}
                    <td class="list-group-item list-group-item-action">
                        <p class="mb-1 message-page-stitle">{{ proposal.title }}</p>
                    </td>
                    <td>
                        <p class="mb-1 message-page-stitle">&nbsp;&nbsp; &nbsp;&nbsp;{{ proposal.expertiseNeeded }}</p>
                    </td>
                    <td>
                        <div class="d-flex w-100 justify-content-between">
                            <small class="text-muted">&nbsp; {{ proposal.city }}</small>
                            <a class="btn-sm btn-primary text-right carrousel-button-uk reserved-remove-underline" role="button"
                               href="{% url 'slavaukraine:proposal' proposal.id  %}">Ver / Editar</a>
                        </div>
                    </td>

                </tr>
                {% endif %}
                {% endfor %}
                {% endif %}

                {% if user.is_person %}
                {% for proposal in proposals %}
                {% if proposal.title != "None" %}
                <td class="list-group-item list-group-item-action">
                    <p class="mb-1 message-page-stitle">{{ proposal.title }}</p>
                </td>
                <td><p class="mb-1 message-page-stitle">&nbsp;&nbsp; &nbsp;&nbsp;{{ proposal.expertiseNeeded }}</p>
                </td>
                <td>
                    <div class="d-flex w-100 justify-content-between">
                        <small class="text-muted">&nbsp; {{ proposal.city }}</small>
                        <a class="btn-sm btn-primary text-right carrousel-button-uk reserved-remove-underline" role="button"
                           href="{% url 'slavaukraine:proposal' proposal.id  %}">Ver / Editar</a>
                    </div>


                </td>
                </tr>

                {% endif %}
                {% endfor %}
                {% endif %}

                </tbody>
            </table>
            <br>
        </div>
        <br>
        {% if user.is_enterprise %}
        <div class="d-inline-flex w-100 justify-content-end">
            <a class="btn-sm btn-primary text-right carrousel-button-uk reserved-remove-underline" role="button"
               href="{% url 'slavaukraine:regist_proposal'  %}">Criar Nova Proposta</a>
        </div>
        {% endif %}
    </div>
    <!-- Favoritos -->
    {% if user.is_person %}
    <div class="tab-pane fade reserved-page-information" id="pills-saved" role="tabpanel"
         aria-labelledby="pills-saved-tab">
        <div class="list-group">
            <table id="table_id4" class="display message-page-mtitle">
                <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Especialidade</th>
                    <th>Localização</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    {% for favorite in favorites %}
                    {% if favorite.title != "None" %}
                    <td class="list-group-item list-group-item-action">
                        <p class="mb-1 message-page-stitle">{{ favorite.title }}</p>
                    </td>
                    <td><p class="mb-1 message-page-stitle">&nbsp;&nbsp; &nbsp;&nbsp;{{ favorite.expertiseNeeded }}</p>
                    </td>
                    <td>
                        <div class="d-flex w-100 justify-content-between">
                            <small class="text-muted">&nbsp; {{ favorite.city }}</small>
                           <a class="btn-sm btn-primary text-right carrousel-button-uk reserved-remove-underline" role="button"
                               href="{% url 'slavaukraine:proposal' favorite.id  %}">Ver / Editar</a>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <br>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css"
      href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript"
        src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable({}
        );
    });

    $(document).ready(function () {
        $('#table_id2').DataTable({}
        );
    });
    $(document).ready(function () {
        $('#table_id4').DataTable({}
        );
    });
</script>
{% endblock %}

rebuildukraine/slavaukraine/templates/slavaukraine/test_editproposal.html
<body>
<form action="" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Envia</button>

</form>